---
title: "Practicum1"
author: "Matt Faucher, Kaelyn Jefferson"
date: "10/19/2021"
output: html_document
---
## Connect to the Database
```{r}
# 1. Library
library(RMySQL)
library(DBI)
# 2. Settings
db_user <- 'root'
db_password <- 'root'
db_name <- 'data'
db_host <- 'localhost'
db_port <- 3306
# 3. Read data from db
con <- dbConnect(MySQL(), user = db_user, password = db_password,
                 dbname = db_name, host = db_host, port = db_port)
```
## Create Incidents Table
```{sql connection=con}
CREATE TABLE IF NOT EXISTS incidents (
  iid INTEGER NOT NULL,
  date DATE NOT NULL,
  depPort VARCHAR(255) NOT NULL,
  arrPort VARCHAR(255) NOT NULL,
  airline VARCHAR(255) NOT NULL DEFAULT 'Unknown',
  aircraft VARCHAR(255) NOT NULL,
  flightPhase VARCHAR(255) NOT NULL,
  impact VARCHAR(255) NOT NULL DEFAULT 'None',
  PRIMARY KEY (iid)
);
```
## Create Lookup table for Airlines
```{sql connection=con}
CREATE TABLE IF NOT EXISTS airlines (
  aid INTEGER NOT NULL,
  code INTEGER NOT NULL,
  airline VARCHAR(255) NOT NULL DEFAULT 'Unknown',
  PRIMARY KEY (aid)
);
```
## Create Index on Airline in Airlines
```{sql connection=con}
CREATE INDEX airline_idx
ON airlines(airline);
```
## Create Lookup table for Airports
```{sql connection=con}
CREATE TABLE IF NOT EXISTS airports (
  pid INTEGER NOT NULL,
  code INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(255),
  state VARCHAR(255) NOT NULL DEFAULT 'N/A',
  country VARCHAR(255) NOT NULL DEFAULT 'USA',
  PRIMARY KEY (pid)
);
```
## Create Index on Code in Airports
```{sql connection=con}
CREATE INDEX code_idx
ON airlines(code);
```
## Add Foreign Key References
```{sql connection=con}
ALTER TABLE incidents
ADD FOREIGN KEY(airline) REFERENCES airlines(airline);
```

```{sql connection=con}
ALTER TABLE airports
ADD FOREIGN KEY(code) REFERENCES airports(code);
```
## Harmonize the flight phases
```{sql connection=con}
CREATE TRIGGER harmonizeFlightPhases
BEFORE INSERT ON incidents
  FOR EACH ROW
  BEGIN
    IF NEW.flightPhase IN ('Take-off run') THEN
      SET NEW.flightPhase = 'takeoff';
    END IF;
    IF NEW.flightPhase IN ('Landing roll') THEN
      SET NEW.flightPhase = 'landing';
    END IF;
    IF NEW.flightPhase IN ('Climb', 'Descent', 'Approach') THEN
      SET NEW.flightPhase = 'inflight';
    ELSE
      SET NEW.flightPhase = 'unknown';
    END IF;
  END;
```
## Disconnect from the Databse
```{r}
dbDisconnect(con)
```